[prometheus-server]
13.235.51.251#<Prometheus_SRV ip>
[prometheus-server:vars]
ansible_ssh_user=ubuntu
ansible_ssh_private_key_file=/home/chi3aev/Ansible-prometheus-grafana/ansible/key.pem
#ansible_ssh_private_key_file=/home/ubuntu/<replace>
